### ISSUE TITLE
Add a statement regarding non-affiliation to actual codechef.com

### ISSUE THREAD

**Issue by atamakahere-git** [ABES-CodeChef/.github#1]
Add a statement where we make clear that "CodeChef ABES EC Chapter" is not. In any way, associated with [CodeChef](https://www.codechef.com/).

It started as codechef chapter earlier, but codechef has dropped their official support for these chapters.

**Comment by dixitsanskar** [comment]
Added line "Disclaimer: The CodeChef ABESEC chapter is a college club and is not affiliated with the official CodeChef organization." in README.md file

**Comment by atamakahere-git** [comment]
closed via f9f62aa
